To_Do_List/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("to_do_app.urls"), name = "todo_app"),
]

to_do_app/urls.py
from django.urls import path
from . import views

app_name = "to_do_app"

urlpatterns = [
        path("", views.ToDoList, name="List"),
        path("<int:pk>/", views.delete_task, name="delete-task"),
]

to_do_app/models.py
from django.db import models

# Create your models here.

class List(models.Model):
    class Meta():
        verbose_name_plural = "List"
    task = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.task

to_do_app/forms.py
from django import forms
from . models import List

class ListModelForm(forms.ModelForm):
    class Meta:
        model = List 
        fields = ("task",)   

to_do_app/views.py
from django.shortcuts import render, redirect
from . models import List
from . forms import ListModelForm
# Create your views here.

def ToDoList(request):
    list_of_task = List.objects.all().order_by("-date_added")
    form = ListModelForm()
    if request.method == "POST":
        form = ListModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    
    context =  {
            "list_of_task" : list_of_task,
            "form": form
    }
    return render(request, "to_do_app/home.html", context)

def delete_task(request, pk):
    task = List.objects.get(id=pk)
    task.delete()
    return redirect("/")
  

to_do_app/templates/to_do_app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do List</title>
</head>
<body>
    <h1>To-Do List</h1>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Task</button>
    </form>
    <ul>
        {% for task in list_of_task %}
            <li>{{ task }}<a href="{% url 'to_do_app:delete-task' task.pk %}"></tr><button type="submit">Delete</button></a><br><br></li>

        {% endfor %}
    </ul>
</body>
</html>